name: CI - Test

on:
  push:

jobs:
  lint:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install project
        run: poetry install --no-interaction

      - name: Test
        run: poetry run task test
